version: '2'
services:
    phpfpm:
        container_name: lemp-fpm$CONTAINER_NAME_SUFFIX
        build:
            args:
                - TZ=$TZ
            context: docker/fpm
        image: lemp-fpm
        network_mode: bridge
        external_links:
            - mysql-container
#            - postgres-container
        volumes:
            - $LEMP_DATA_FOLDER:/srv/web
        environment:
            - LEMP_DATA_FOLDER=$LEMP_DATA_FOLDER
            - LEMP_PORT=$LEMP_PORT
            - LEMP_SSL_PORT=$LEMP_SSL_PORT

    nginx:
        container_name: lemp-nginx$CONTAINER_NAME_SUFFIX
        build:
            args:
                - TZ=$TZ
            context: docker/nginx
        network_mode: bridge
        image: lemp-nginx
        links:
            - phpfpm
        volumes_from:
            - phpfpm
        ports:
            - "$LEMP_PORT:80"
            - "$LEMP_SSL_PORT:443"
        environment:
            - LEMP_DATA_FOLDER=$LEMP_DATA_FOLDER
            - LEMP_PORT=$LEMP_PORT
            - LEMP_SSL_PORT=$LEMP_SSL_PORT
